// Contract ABIs for Magic Stone frontend
// These are minimal ABIs containing only the functions used by the UI.
// Full ABIs are in artifacts/contracts/*.json (generated by Hardhat, not tracked in git).
// To regenerate: run `npx hardhat compile` then copy the "abi" arrays from the artifact JSONs.

export const STONE_NFT_ABI = [
  "constructor()",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "function getStoneProps(uint256 id) view returns (uint8, uint256, uint256, bool)",
  "function mintStone(address to, uint8 grade, uint256 damageLimit, bool mysterious) returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function approve(address to, uint256 tokenId)",
  "function setPolishingContract(address _p)",
  "function increaseDamage(uint256 id, uint256 value)",
  "function setGrade(uint256 id, uint8 newGrade)",
];

export const TOOL_NFT_ABI = [
  "constructor()",
  "function mintTool(address to, uint8 level, uint256 durabilityMax) returns (uint256)",
  "function getToolProps(uint256 id) view returns (uint8, uint256, uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function approve(address to, uint256 tokenId)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function setPolishingContract(address _p)",
  "function decreaseDurability(uint256 id, uint256 value)",
];

export const GAME_TOKEN_ABI = [
  "constructor()",
  "function mint(address to, uint256 amount)",
  "function balanceOf(address account) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
];

export const POLISHING_ABI = [
  "constructor(address _stone, address _tool)",
  "event Polished(address indexed user, uint256 stoneId, uint256 toolId, bool upgraded, uint8 newGrade)",
  "function polish(uint256 stoneId, uint256 toolId)",
];

export const MARKET_ABI = [
  "constructor(address _stone, address _tool, address _token)",
  "event Listed(address indexed seller, bool isStone, uint256 tokenId, uint256 price)",
  "event Sold(address indexed buyer, address indexed seller, bool isStone, uint256 tokenId, uint256 price)",
  "function list(bool _isStone, uint256 tokenId, uint256 price)",
  "function buy(bool _isStone, uint256 tokenId)",
];

export const QUEST_ABI = [
  "constructor(address _token)",
  "event QuestCompleted(address indexed user, uint256 indexed questId)",
  "event RewardClaimed(address indexed user, uint256 indexed questId, uint256 reward)",
  "function createQuest(uint8 questType, string description, uint256 reward)",
  "function assignQuestToUser(address user, uint256 questId)",
  "function claimReward(uint256 questId)",
];
