// Contract ABIs for Magic Stone frontend
// These are minimal ABIs containing only the functions used by the UI.
// Full ABIs are in artifacts/contracts/*.json (generated by Hardhat, not tracked in git).
// To regenerate: run `npx hardhat compile` then copy the "abi" arrays from the artifact JSONs.

export const STONE_NFT_ABI = [
  "constructor()",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "function getStoneProps(uint256 id) view returns (uint8, uint8, uint256, uint256, bool)",
  "function mintStone(address to, uint8 grade, uint8 subGrade, uint256 damageLimit, bool mysterious) returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function approve(address to, uint256 tokenId)",
  "function setPolishingContract(address _p)",
  "function increaseDamage(uint256 id, uint256 value)",
  "function setGrade(uint256 id, uint8 newGrade)",
  "function setSubGrade(uint256 id, uint8 newSubGrade)",
];

export const TOOL_NFT_ABI = [
  "constructor()",
  "function mintTool(address to, uint8 level, uint256 durabilityMax) returns (uint256)",
  "function getToolProps(uint256 id) view returns (uint8, uint256, uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function approve(address to, uint256 tokenId)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function setPolishingContract(address _p)",
  "function decreaseDurability(uint256 id, uint256 value)",
  "function craftTool(uint256 id1, uint256 id2, uint256 id3) returns (uint256)",
  "event Crafted(address indexed user, uint8 fromLevel, uint8 toLevel, uint256 newId)",
];

export const GAME_TOKEN_ABI = [
  "constructor()",
  "function mint(address to, uint256 amount)",
  "function balanceOf(address account) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
];

export const POLISHING_ABI = [
  "constructor(address _stone, address _tool)",
  "event Polished(address indexed user, uint256 stoneId, uint256 toolId, bool upgraded, uint8 newGrade, uint8 newSubGrade)",
  "function polish(uint256 stoneId, uint256 toolId)",
];

export const MARKET_ABI = [
  "constructor(address _stone, address _tool, address _token)",
  "event Listed(address indexed seller, bool isStone, uint256 indexed tokenId, uint256 price)",
  "event Delisted(address indexed seller, bool isStone, uint256 indexed tokenId)",
  "event Sold(address indexed buyer, address indexed seller, bool isStone, uint256 indexed tokenId, uint256 price, uint256 fee)",
  "event OfferMade(address indexed buyer, bool isStone, uint256 indexed tokenId, uint256 price)",
  "event OfferCancelled(address indexed buyer, bool isStone, uint256 indexed tokenId)",
  "event OfferAccepted(address indexed buyer, address indexed seller, bool isStone, uint256 indexed tokenId, uint256 price, uint256 fee)",
  "function list(bool _isStone, uint256 tokenId, uint256 price)",
  "function delist(bool _isStone, uint256 tokenId)",
  "function buy(bool _isStone, uint256 tokenId)",
  "function makeOffer(bool _isStone, uint256 tokenId, uint256 price)",
  "function cancelOffer(bool _isStone, uint256 tokenId)",
  "function acceptOffer(bool _isStone, uint256 tokenId, address buyer)",
  "function getOffer(bool _isStone, uint256 tokenId) view returns (address buyer, uint256 price, bool active)",
  "function getSaleHistory(bool _isStone, uint256 tokenId) view returns (uint256[])",
  "event AuctionStarted(address indexed seller, bool isStone, uint256 indexed tokenId, uint256 startPrice, uint256 endTime)",
  "event AuctionBid(address indexed bidder, bool isStone, uint256 indexed tokenId, uint256 bid)",
  "event AuctionSettled(address indexed winner, address indexed seller, bool isStone, uint256 indexed tokenId, uint256 price, uint256 fee)",
  "event AuctionCancelled(address indexed seller, bool isStone, uint256 indexed tokenId)",
  "function startAuction(bool _isStone, uint256 tokenId, uint256 _startPrice, uint256 _minBidIncrement, uint256 _duration)",
  "function bid(bool _isStone, uint256 tokenId, uint256 _bidAmount)",
  "function settleAuction(bool _isStone, uint256 tokenId)",
  "function cancelAuction(bool _isStone, uint256 tokenId)",
  "function getAuction(bool _isStone, uint256 tokenId) view returns (address seller, uint256 startPrice, uint256 minBidIncrement, uint256 endTime, address highestBidder, uint256 highestBid, bool active)",
  "function feeBps() view returns (uint256)",
  "function feeReceiver() view returns (address)",
];

export const QUEST_ABI = [
  "constructor(address _token)",
  "event QuestCreated(uint256 indexed questId, uint8 questType, uint256 reward)",
  "event QuestCompleted(address indexed user, uint256 indexed questId)",
  "event RewardClaimed(address indexed user, uint256 indexed questId, uint256 reward)",
  "function createQuest(uint8 questType, string description, uint256 reward)",
  "function setQuestActive(uint256 questId, bool _active)",
  "function assignQuestToUser(address user, uint256 questId)",
  "function updateProgress(address user, uint256 questId, uint256 increment)",
  "function claimReward(uint256 questId)",
  "function getQuestCount() view returns (uint256)",
  "function getQuestInfo(uint256 questId) view returns (uint8 questType, string description, uint256 reward, bool active)",
  "function getUserQuestIds(address user) view returns (uint256[] memory)",
  "function userProgress(address user, uint256 questId) view returns (uint256 questId, uint256 progress, bool completed, uint256 claimedAt)",
];
